//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_CommonCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dc_CommonCourse()
        {
            this.dc_Common_Course_Teacher = new HashSet<dc_Common_Course_Teacher>();
            this.dc_CourseFavorite = new HashSet<dc_CourseFavorite>();
        }
    
        public int CourseID { get; set; }
        public int ClassID { get; set; }
        public string CourseName { get; set; }
        public string SubTitle { get; set; }
        public string CoursePic { get; set; }
        public byte CourseOrder { get; set; }
        public string CourseIntro { get; set; }
        public string CourseDetail { get; set; }
        public bool IsHome { get; set; }
        public System.DateTime AddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_Common_Course_Teacher> dc_Common_Course_Teacher { get; set; }
        public virtual dc_CommonCourseClass dc_CommonCourseClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_CourseFavorite> dc_CourseFavorite { get; set; }
    }
}
