//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_CourseFavorite
    {
        public int FavoriteID { get; set; }
        public int EnterpriseID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime FavoriteTime { get; set; }
    
        public virtual dc_CommonCourse dc_CommonCourse { get; set; }
        public virtual dc_Enterprise dc_Enterprise { get; set; }
    }
}
