//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dc_Course()
        {
            this.dc_Course_Teacher = new HashSet<dc_Course_Teacher>();
            this.dc_Enroll = new HashSet<dc_Enroll>();
        }
    
        public int CourseID { get; set; }
        public int EnterpriseID { get; set; }
        public string CourseName { get; set; }
        public string SubTitle { get; set; }
        public string CoursePic { get; set; }
        public byte CourseOrder { get; set; }
        public string CourseIntro { get; set; }
        public string CourseDetail { get; set; }
        public Nullable<System.DateTime> ClassTime { get; set; }
        public string ClassPlace { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public string QRCode { get; set; }
        public byte CourseState { get; set; }
        public int SignupCount { get; set; }
        public int SigninCount { get; set; }
        public bool IsHome { get; set; }
        public System.DateTime AddTime { get; set; }
    
        public virtual dc_Enterprise dc_Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_Course_Teacher> dc_Course_Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_Enroll> dc_Enroll { get; set; }
    }
}
