//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_Notice_Staff
    {
        public int ID { get; set; }
        public int StaffID { get; set; }
        public int NoticeID { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
    
        public virtual dc_Notice dc_Notice { get; set; }
        public virtual dc_Staff dc_Staff { get; set; }
    }
}
