//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_UserItemsClass
    {
        public int ClassID { get; set; }
        public string ClassName { get; set; }
        public int ParentID { get; set; }
        public string ParentPath { get; set; }
        public int Depth { get; set; }
        public int Child { get; set; }
        public int OrderID { get; set; }
        public byte LanType { get; set; }
        public string LinkUrl { get; set; }
    }
}
