//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dc_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dc_User()
        {
            this.dc_Enterprise = new HashSet<dc_Enterprise>();
            this.dc_Staff = new HashSet<dc_Staff>();
        }
    
        public int UserID { get; set; }
        public byte UserType { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public int LoginNum { get; set; }
        public bool IsLock { get; set; }
        public string Token { get; set; }
        public System.DateTime AddTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_Enterprise> dc_Enterprise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dc_Staff> dc_Staff { get; set; }
    }
}
