//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dechengEntities : DbContext
    {
        public dechengEntities()
            : base("name=dechengEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dc_Admin> dc_Admin { get; set; }
        public virtual DbSet<dc_Common_Course_Teacher> dc_Common_Course_Teacher { get; set; }
        public virtual DbSet<dc_CommonCourse> dc_CommonCourse { get; set; }
        public virtual DbSet<dc_CommonCourseClass> dc_CommonCourseClass { get; set; }
        public virtual DbSet<dc_CommonTeacher> dc_CommonTeacher { get; set; }
        public virtual DbSet<dc_Course> dc_Course { get; set; }
        public virtual DbSet<dc_Course_Teacher> dc_Course_Teacher { get; set; }
        public virtual DbSet<dc_CourseEnroll> dc_CourseEnroll { get; set; }
        public virtual DbSet<dc_CourseFavorite> dc_CourseFavorite { get; set; }
        public virtual DbSet<dc_Enroll> dc_Enroll { get; set; }
        public virtual DbSet<dc_Enterprise> dc_Enterprise { get; set; }
        public virtual DbSet<dc_Log> dc_Log { get; set; }
        public virtual DbSet<dc_Mail> dc_Mail { get; set; }
        public virtual DbSet<dc_MailSend> dc_MailSend { get; set; }
        public virtual DbSet<dc_Message> dc_Message { get; set; }
        public virtual DbSet<dc_Notice> dc_Notice { get; set; }
        public virtual DbSet<dc_Notice_Staff> dc_Notice_Staff { get; set; }
        public virtual DbSet<dc_Roles> dc_Roles { get; set; }
        public virtual DbSet<dc_RolesItem> dc_RolesItem { get; set; }
        public virtual DbSet<dc_Shortcut> dc_Shortcut { get; set; }
        public virtual DbSet<dc_Staff> dc_Staff { get; set; }
        public virtual DbSet<dc_Student> dc_Student { get; set; }
        public virtual DbSet<dc_SysConfig> dc_SysConfig { get; set; }
        public virtual DbSet<dc_SysItemsClass> dc_SysItemsClass { get; set; }
        public virtual DbSet<dc_Teacher> dc_Teacher { get; set; }
        public virtual DbSet<dc_User> dc_User { get; set; }
        public virtual DbSet<dc_UserItemsClass> dc_UserItemsClass { get; set; }
        public virtual DbSet<View_dc_Course> View_dc_Course { get; set; }
        public virtual DbSet<View_dc_Favorite> View_dc_Favorite { get; set; }
        public virtual DbSet<View_dc_Feedback> View_dc_Feedback { get; set; }
        public virtual DbSet<View_dc_MailList> View_dc_MailList { get; set; }
        public virtual DbSet<View_dc_Message> View_dc_Message { get; set; }
        public virtual DbSet<View_dc_Message_Enterprise> View_dc_Message_Enterprise { get; set; }
        public virtual DbSet<View_dc_Message_Staff> View_dc_Message_Staff { get; set; }
        public virtual DbSet<View_dc_SendMail> View_dc_SendMail { get; set; }
        public virtual DbSet<View_dc_Sign> View_dc_Sign { get; set; }
        public virtual DbSet<VIEW_NAME> VIEW_NAME { get; set; }
    
        public virtual ObjectResult<Log_List_Result> Log_List(Nullable<int> pageIndex, Nullable<int> pageSize, string userName, ObjectParameter totalCount)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Log_List_Result>("Log_List", pageIndexParameter, pageSizeParameter, userNameParameter, totalCount);
        }
    
        public virtual ObjectResult<Log_PageList_Result> Log_PageList(Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter pageCount, ObjectParameter totalCount, string userName)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Log_PageList_Result>("Log_PageList", pageIndexParameter, pageSizeParameter, pageCount, totalCount, userNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LogList(Nullable<int> pageIndex, Nullable<int> pageSize, string userName, ObjectParameter pageCount, ObjectParameter totalCount)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LogList", pageIndexParameter, pageSizeParameter, userNameParameter, pageCount, totalCount);
        }
    
        public virtual ObjectResult<proc_LogList_Result> proc_LogList(string userName, string description, Nullable<int> pageIndex, Nullable<int> pageSize, ObjectParameter totalCount, ObjectParameter pageCount)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_LogList_Result>("proc_LogList", userNameParameter, descriptionParameter, pageIndexParameter, pageSizeParameter, totalCount, pageCount);
        }
    }
}
