//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dc_Favorite
    {
        public string ClassName { get; set; }
        public int CourseID { get; set; }
        public int ClassID { get; set; }
        public string CourseName { get; set; }
        public string SubTitle { get; set; }
        public string CoursePic { get; set; }
        public byte CourseOrder { get; set; }
        public string CourseIntro { get; set; }
        public string CourseDetail { get; set; }
        public bool IsHome { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime FavoriteTime { get; set; }
        public int EnterpriseID { get; set; }
        public string EnterpriseName { get; set; }
        public int FavoriteID { get; set; }
    }
}
