//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRBAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_dc_Course
    {
        public int CourseID { get; set; }
        public int EnterpriseID { get; set; }
        public string CourseName { get; set; }
        public string SubTitle { get; set; }
        public Nullable<System.DateTime> ClassTime { get; set; }
        public string ClassPlace { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
        public byte CourseState { get; set; }
        public int SignupCount { get; set; }
        public int SigninCount { get; set; }
        public bool IsHome { get; set; }
        public System.DateTime AddTime { get; set; }
        public string FullName { get; set; }
        public int EnrollID { get; set; }
        public Nullable<System.DateTime> SignupTime { get; set; }
        public Nullable<System.DateTime> SigninTime { get; set; }
        public int StaffID { get; set; }
        public bool Gender { get; set; }
        public string Email { get; set; }
    }
}
